name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: touch environments/cc3/devnet/.env
      - run: touch environments/cc3/devnet/.private.seed
      - run: echo "disorder match oven ship cancel act scatter material country lizard glance record" > environments/cc3/devnet/.private.seed
      - run: echo "CRUNCH_STASHES=5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY\n" > environments/cc3/devnet/.env
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: docker/devnet.dockerfile
          push: false
          tags: crunch/app:latest

      