name: Devnet ci

on:
  push:
    branches:
      - 'devnet'
jobs:
  devnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up account private key
        run: |
          echo "${{ secrets.DEVNET_CRUNCH_PK }}" >> environments/cc3/devnet/.private.seed
          
      - name: Set up Crunch configuration
        run: |
          echo "${{ secrets.DEVNET_CRUNCH_CONFIG }}" >> environments/cc3/devnet/.env

      - name: Check settings
        run: |
          ls -a environments/cc3/devnet/

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/devnet.dockerfile
          push: true
          tags: gluwa/crunch-devnet:latest

      
