name: Release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "release/*"

permissions: read-all

jobs:
  ## not sure if having multiple private seeds break image so splitting it up by network still
  build-container-image:
    strategy:
      fail-fast: false
      matrix:
        network: [devnet, testnet, mainnet]
    name: build-container-image-for-${{ matrix.network }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # TODO: unify these 3 steps
      - name: Set up account private key for devnet
        if: matrix.network == 'devnet'
        run: |
          echo "${{ secrets.DEVNET_CRUNCH_PK }}" >> environments/cc3/${{ matrix.network }}/.private.seed

      - name: Set up account private key for testnet
        if: matrix.network == 'testnet'
        run: |
          echo "${{ secrets.TESTNET_CRUNCH_PK }}" >> environments/cc3/${{ matrix.network }}/.private.seed

      - name: Set up account private key for mainnet
        if: matrix.network == 'mainnet'
        run: |
          echo "${{ secrets.MAINNET_CRUNCH_PK }}" >> environments/cc3/${{ matrix.network }}/.private.seed

      # TODO: is this valid only for mainnet or for all images ?
      - name: Set up config for mainnet
        if: matrix.network == 'mainnet'
        run: |
          echo "${{ secrets.MAINNET_CRUNCH_CONFIG }}" > environments/cc3/${{ matrix.network }}/.env

      - name: Check settings
        run: |
          ls -a environments/cc3/${{ matrix.network }}/

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            NETWORK=${{ matrix.network }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: gluwa/crunch:${{ matrix.network }}-${{github.run_id}}
