name: Testnet ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'testnet'
jobs:
  testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - shell: bash
        env:
          CRUNCH_AGENT_PK: ${{ secrets.TESTNET_CRUNCH_PK }}  
        run: |
          touch environments/cc3/testnet/.private.seed \
            && echo $CRUNCH_AGENT_PK > environments/cc3/testnet/.private.seed
      - shell: bash
        env:
          CRUNCH_AGENT_CONFIG: ${{ secrets.TESTNET_CRUNCH_CONFIG }}  
        run: |
          touch environments/cc3/testnet/.env \
            && echo $CRUNCH_AGENT_CONFIG > environments/cc3/testnet/.env

      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          file: docker/testnet.dockerfile
          push: true
          tags: gluwa/crunch:testnet-${{github.run_id}}

      