name: Testnet CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'testnet'
jobs:
  testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up account private key
        run: |
          echo "${{ secrets.TESTNET_CRUNCH_PK }}" >> environments/cc3/testnet/.private.seed
          
      - name: Set up Crunch configuration
        run: |
          echo "${{ secrets.TESTNET_CRUNCH_CONFIG }}" >> environments/cc3/testnet/.env

      - name: Check settings
        run: |
          ls -a environments/cc3/testnet/
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: docker/testnet.dockerfile
          push: true
          tags: gluwa/crunch:testnet-${{github.run_id}}

      
